version: '3.7'
services:

    php-fpm:
        image: ${REGISTRY}/numgen-app-php-fpm:${IMAGE_TAG}
        environment:
            ENV: ${ENV}
        volumes:
            - ./:/var/www/html

    php-cli:
        image: ${REGISTRY}/numgen-app-php-cli:${IMAGE_TAG}
        environment:
            ENV: ${ENV}
        volumes:
            - ./:/app

    nginx:
        image: ${REGISTRY}/numgen-nginx:${IMAGE_TAG}
        ports:
            - ${APP_WEB_PORT}:80
        volumes:
            - ./:/var/www/html